### ЗАПРОСЫ


### Регистрация пользователя
### Указать "type": "shop" для создания магазина
### Почту необходимо указывать реальную, иначе доступ к сервису будет недоступен
POST http://127.0.0.1:8000/user/register
Content-Type: application/json

{
    "first_name": "Paul",
    "last_name" : "Wesson",
    "email": "wesson@box.com",
    "password": "password"
    
}

### Подтверждение почты
### После регистрации на почту придёт ссылка с токеном, который нужно отправить в ответ
POST http://127.0.0.1:8000/user/confirm
Content-Type: application/json

{
    "email": "wesson@box.com",
    "token": "886c39faf1253eb1b20576e2684828d889686"
    
}

### Логин пользователя
### После логирования будут доступны остальные ссылки, путём получения Токена от БД
POST http://127.0.0.1:8000/user/login
Content-Type: application/json

{
    "email": "wesson@box.com",
    "password": "password"
    
}

### Добавление контактов пользователя
POST http://127.0.0.1:8000/user/contact
Content-Type: application/json
Authorization: token 38de7958cdd5fd9469c121499768eb98788b57e0

{
    "city": "Moscow",
    "street": "Beloborodova St., 4",
    "phone": "893723123123" 
}

### Просмотр контактов
GET http://127.0.0.1:8000/user/contact
Content-Type: application/json
Authorization: token 38de7958cdd5fd9469c121499768eb98788b57e0







### МАГАЗИНЫ


### Список магазинов
GET http://127.0.0.1:8000/shops
Content-Type: application/json


### Список Категорий
GET http://127.0.0.1:8000/categories
Content-Type: application/json

### Список товаров
### Можно указывать ID магазина либо ID категории для поиска товаров
GET http://127.0.0.1:8000/products?shop_id=1
Content-Type: application/json







### КОРЗИНА


### Создать заказ и заполнить корзину
POST http://127.0.0.1:8000/basket
Content-Type: application/json
Authorization: token 94e1880d42d8588f3745bf3e5fd374212aa8acb0

{
    "items":
        {
            "product_info": 6,
            "quantity": 1,
        }
}

### Удаление позиции из заказа
DELETE http://127.0.0.1:8000/basket
Content-Type: application/json
Authorization: token 94e1880d42d8588f3745bf3e5fd374212aa8acb0

{
    "items":
        {
            "id": 1
        }
}

### Изменение позиции в заказе
PUT http://127.0.0.1:8000/basket
Content-Type: application/json
Authorization: token 94e1880d42d8588f3745bf3e5fd374212aa8acb0

{
    "items":
        {
            "id": 5,
            "quantity": 1
        }
}

### Получить корзину
GET http://127.0.0.1:8000/basket
Content-Type: application/json
Authorization: token 94e1880d42d8588f3745bf3e5fd374212aa8acb0







### ЗАКАЗЫ ПОКУПАТЕЛЕЙ

### Посмотреть заказ
GET http://127.0.0.1:8000/order
Content-Type: application/json
Authorization: token 94e1880d42d8588f3745bf3e5fd374212aa8acb0

### Разместить заказ
POST http://127.0.0.1:8000/order
Content-Type: application/json
Authorization: token 94e1880d42d8588f3745bf3e5fd374212aa8acb0

{
    "id": 1,
    "contact": 1
}







### ДЛЯ ПОСТАВЩИКОВ


### Получить статус магазина
GET http://127.0.0.1:8000/partner/state
Content-Type: application/json
Authorization: token 04c5752b60b903bb2dc95ecf2ecf43c113489f0b

### Изменить статус магазина
POST http://127.0.0.1:8000/partner/state
Content-Type: application/json
Authorization: token 04c5752b60b903bb2dc95ecf2ecf43c113489f0b

{
    "state": true
}

### Посмотреть заказы для поставщиков
GET http://127.0.0.1:8000/partner/orders
Content-Type: application/json
Authorization: token 38de7958cdd5fd9469c121499768eb98788b57e0

### Обновление прайса
POST http://127.0.0.1:8000/partner/update
Content-Type: application/json
Authorization: token 38de7958cdd5fd9469c121499768eb98788b57e0

{
    "items":
        {
            "shop_id": 1,
            "product_id": 4,
            "name": "MAC",
            "quantity": 4,
            "price": 1290

        }
}