# Generated by Django 4.2.7 on 2023-11-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='token',
            field=models.CharField(blank=True, max_length=16, unique=True, verbose_name='token'),
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, max_length=16, unique=True, verbose_name='token'),
        ),
    ]
